apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: test-secret
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./custom_tests
  sourceRef:
    kind: GitRepository
    name: test-secret
    namespace: flux-system
